import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRight, Bell, BellOff, Check, ChevronDown, Cloud, CloudOff, Coffee, Compass, Heart, Lightbulb, Menu, MessageCircle, Moon, MoreHorizontal, Plus, Send, Settings2, ShieldCheck, Sparkles, Target, Trash2, WandSparkles, X } from 'lucide-react';
import mark from './assets/bro-mark.svg';
import mascot from './assets/bro-mascot.svg';
import sky from './assets/empty-sky.svg';
import type { AppData, ChatMessage, Conversation, Frequency, Goal, Profile, Settings } from './lib/model';
import { frequencyMs, isQuiet, localPreviewResponse, readData, saveData } from './lib/model';
import { cloudConfigured, getCloudMessages, loadCloud, removeGoal, requestChat, requestCheckin, saveConversation, saveGoal, syncProfile } from './lib/cloud';

type View = 'chat' | 'goals' | 'settings';
type Mode = 'connecting' | 'cloud' | 'preview';
const suggestions = [
 {icon:Lightbulb,label:'Brainstorm an idea',prompt:'yo, i have an idea. help me figure it out.'},
 {icon:Target,label:'Make some progress',prompt:'bro, help me take the next step on my goal.'},
 {icon:Coffee,label:'Just hang out',prompt:"yo, what's good?"}
];
const uid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const time=(date:string)=>new Date(date).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
const errorText=(e:unknown)=>e instanceof Error?e.message:'Something went wrong. Try again.';
function Logo({compact=false}:{compact?:boolean}){return <div className="logo"><img src={mark} alt="BRO icon"/>{!compact&&<strong>bro<span>.</span></strong>}</div>;}
function Toggle({value,onChange,label}:{value:boolean;onChange:(v:boolean)=>void;label:string}){return <button type="button" className={'toggle '+(value?'on':'')} aria-label={label} aria-pressed={value} onClick={()=>onChange(!value)}><i/></button>;}
function Onboarding({onFinish}:{onFinish:(profile:Profile,goal:string,proactive:boolean)=>void}){
 const [step,setStep]=useState(0),[name,setName]=useState(''),[occupation,setOccupation]=useState(''),[about,setAbout]=useState(''),[goal,setGoal]=useState(''),[proactive,setProactive]=useState(false);
 return <main className="onboard"><div className="onboard-glow glow-a"/><div className="onboard-glow glow-b"/><div className="onboard-wrap">
 <div className="onboard-top"><Logo/><span>GETTING TO KNOW YOU <b>{step+1} / 3</b></span></div>
 <div className="progress"><i style={{width:String((step+1)/3*100)+'%'}}/></div>
 <section className="onboard-card" key={step}><img className="onboard-mascot" src={mascot} alt="BRO waving hello"/>
 {step===0?<><p className="eyebrow"><Sparkles size={15}/> THE START OF SOMETHING GOOD</p><h1>yo, i'm BRO. <em>what's your name?</em></h1><p>Not another robot asking you to fill out a boring form. Let's actually get to know each other.</p><label htmlFor="your-name">WHAT SHOULD I CALL YOU?</label><input id="your-name" autoFocus placeholder="Your first name" maxLength={50} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&name.trim())setStep(1);}}/><button className="primary full" disabled={!name.trim()} onClick={()=>setStep(1)}>nice to meet you <ArrowRight size={18}/></button></>:
 step===1?<><p className="eyebrow"><Compass size={15}/> YOUR WORLD</p><h1>so, {name.trim()}... <em>what's your thing?</em></h1><p>Student? Creator? Founder? Still figuring it out? All of the above is valid.</p><label htmlFor="occupation">WHAT DO YOU DO?</label><input id="occupation" autoFocus placeholder="e.g. designer, student, indie hacker" maxLength={90} value={occupation} onChange={e=>setOccupation(e.target.value)}/><label htmlFor="about">TELL ME A BIT MORE (OPTIONAL)</label><textarea id="about" rows={3} maxLength={500} placeholder="What are you into lately?" value={about} onChange={e=>setAbout(e.target.value)}/><button className="primary full" disabled={!occupation.trim()} onClick={()=>setStep(2)}>keep going <ArrowRight size={18}/></button></>:
 <><p className="eyebrow"><Target size={15}/> LET'S BUILD SOMETHING</p><h1>one last thing. <em>what's your big goal?</em></h1><p>Could be anything. I'll remember it and help you make it happen. No pressure.</p><label htmlFor="goal">WHAT ARE YOU WORKING TOWARD?</label><textarea id="goal" autoFocus rows={3} maxLength={200} placeholder="e.g. launch my first app, get fit, start creating..." value={goal} onChange={e=>setGoal(e.target.value)}/><div className="optin"><div><b>let me text first ✨</b><small>Allow occasional check-ins and notifications. Change this anytime.</small></div><Toggle label="Enable proactive check-ins" value={proactive} onChange={setProactive}/></div><button className="primary full" onClick={()=>onFinish({name:name.trim(),occupation:occupation.trim(),about:about.trim(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/New_York',onboarded:true},goal.trim(),proactive)}>let's go, bro <ArrowRight size={18}/></button><small className="tiny-center">You're in control. BRO is an AI, not a person.</small></>}
 </section><p className="onboard-footer"><ShieldCheck size={15}/> Private to your account. You choose when BRO checks in.</p></div></main>;
}
function Bubble({message}:{message:ChatMessage}){const ai=message.role==='assistant';return <article className={'bubble-row '+(ai?'ai':'mine')}>{ai&&<img className="avatar" src={mark} alt="BRO"/>}<div className="bubble-body">{ai&&<div className="speaker">bro {message.source==='proactive'&&<span className="proactive-label">texted first ✨</span>} <time>{time(message.created_at)}</time></div>}<div className="bubble">{message.content}</div>{!ai&&<time className="mine-time">{time(message.created_at)}</time>}</div></article>;}
export default function App(){
 const [splash,setSplash]=useState(true);
 const [data,setData]=useState<AppData>(()=>readData());
 const dataRef=useRef(data);dataRef.current=data;
 const [mode,setMode]=useState<Mode>(cloudConfigured?'connecting':'preview');
 const modeRef=useRef(mode);modeRef.current=mode;
 const [view,setView]=useState<View>('chat');
 const [composer,setComposer]=useState('');
 const [goalText,setGoalText]=useState('');
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [menuOpen,setMenuOpen]=useState(false);
 const endRef=useRef<HTMLDivElement|null>(null);
 const checkBusy=useRef(false);
 useEffect(()=>{const timer=setTimeout(()=>setSplash(false),1750);return()=>clearTimeout(timer);},[]);
 useEffect(()=>{saveData(data);},[data]);
 useEffect(()=>{if(!cloudConfigured)return;let canceled=false;loadCloud(dataRef.current).then(async remote=>{if(canceled)return;setData(remote);setMode('cloud');if(remote.profile.onboarded)await syncProfile(remote.profile,remote.settings);}).catch(e=>{if(!canceled){setMode('preview');setError('Cloud connection failed: '+errorText(e)+'. Local preview is available.');}});return()=>{canceled=true;};},[]);
 const active=data.conversations.find(c=>c.id===data.activeConversationId);
 const shown=data.messages.filter(m=>m.conversation_id===data.activeConversationId);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'});},[shown.length,data.activeConversationId,busy]);
 const warn=(e:unknown)=>setError(errorText(e));
 const persistProfile=(p:Profile,s:Settings)=>{if(modeRef.current==='cloud')void syncProfile(p,s).catch(warn);};
 const patchSettings=(patch:Partial<Settings>)=>{const d=dataRef.current;const s={...d.settings,...patch};setData(x=>({...x,settings:s}));persistProfile(d.profile,s);};
 const makeConversation=():Conversation=>({id:uid(),title:'New chat',created_at:now()});
 const newChat=()=>{const c=makeConversation();setData(d=>({...d,activeConversationId:c.id,conversations:[c,...d.conversations]}));setView('chat');setMenuOpen(false);if(modeRef.current==='cloud')void saveConversation(c).catch(warn);};
 const finish=(p:Profile,goal:string,proactive:boolean)=>{const c=makeConversation();const g:Goal|null=goal?{id:uid(),title:goal,done:false,created_at:now()}:null;const settings={...dataRef.current.settings,proactive,notifications:proactive};setData(d=>({...d,profile:p,settings,conversations:[c],activeConversationId:c.id,goals:g?[g]:[],lastLocalCheckin:now()}));setView('chat');if(modeRef.current==='cloud'){void (async()=>{try{await syncProfile(p,settings);await saveConversation(c);if(g)await saveGoal(g);}catch(e){warn(e);}})();}};
 const send=async(input?:string)=>{const text=(input??composer).trim();if(!text||busy||text.length>3000)return;const state=dataRef.current;let c=state.conversations.find(x=>x.id===state.activeConversationId);if(!c)c=makeConversation();const conversation=c;const user:ChatMessage={id:uid(),conversation_id:conversation.id,role:'user',content:text,source:'chat',created_at:now()};setComposer('');setError('');setBusy(true);
 setData(d=>({...d,activeConversationId:conversation.id,conversations:d.conversations.some(x=>x.id===conversation.id)?d.conversations.map(x=>x.id===conversation.id&&x.title==='New chat'?{...x,title:text.slice(0,36)}:x):[{...conversation,title:text.slice(0,36)},...d.conversations],messages:[...d.messages,user]}));
 try{if(modeRef.current==='cloud'){await saveConversation({...conversation,title:conversation.title==='New chat'?text.slice(0,36):conversation.title});const reply=await requestChat(conversation.id,text,user.id);setData(d=>({...d,messages:d.messages.some(m=>m.id===reply.id)?d.messages:[...d.messages,reply]}));}
 else{await new Promise(resolve=>setTimeout(resolve,650));const reply:ChatMessage={id:uid(),conversation_id:conversation.id,role:'assistant',content:localPreviewResponse(text,state.profile,state.goals),source:'chat',created_at:now()};setData(d=>({...d,messages:[...d.messages,reply]}));}}
 catch(e){warn(e);}finally{setBusy(false);}
 };
 const checkin=useCallback(async()=>{const d=dataRef.current;const m=modeRef.current;if(checkBusy.current||!d.profile.onboarded||!d.settings.proactive||!d.settings.notifications||isQuiet(d.settings))return;checkBusy.current=true;
 try{if(m==='cloud'){const remote=await getCloudMessages();let fresh:ChatMessage[]=[];setData(current=>{const known=new Set(current.messages.map(x=>x.id));fresh=remote.filter(x=>!known.has(x.id));return fresh.length?{...current,messages:[...current.messages,...fresh],activeConversationId:current.activeConversationId||fresh[0].conversation_id}:current;});for(const x of fresh.filter(x=>x.source==='proactive'))void window.broDesktop?.notify('BRO texted you 💙',x.content);await requestCheckin();const updated=await getCloudMessages();let added:ChatMessage[]=[];setData(current=>{const known=new Set(current.messages.map(x=>x.id));added=updated.filter(x=>!known.has(x.id));return added.length?{...current,messages:[...current.messages,...added],activeConversationId:current.activeConversationId||added[0].conversation_id}:current;});for(const x of added.filter(x=>x.source==='proactive'))void window.broDesktop?.notify('BRO texted you 💙',x.content);}
 else if(m==='preview'&&d.activeConversationId){if(d.lastLocalCheckin&&Date.now()-new Date(d.lastLocalCheckin).getTime()<frequencyMs(d.settings.frequency))return;const goal=d.goals.find(x=>!x.done);const content=goal?'yo '+d.profile.name.split(' ')[0]+', how’s “'+goal.title+'” going? wanna make a little progress? 👀':'yo, what’s good? got anything you wanna work on today?';const item:ChatMessage={id:uid(),conversation_id:d.activeConversationId,role:'assistant',content,source:'proactive',created_at:now()};setData(current=>({...current,lastLocalCheckin:now(),messages:[...current.messages,item]}));void window.broDesktop?.notify('BRO texted you 💙',content);}}
 catch(e){console.error('Check-in failed',e);}finally{checkBusy.current=false;}},[]);
 useEffect(()=>{const id=setInterval(()=>void checkin(),60_000);const unsub=window.broDesktop?.onTick(()=>void checkin());return()=>{clearInterval(id);unsub?.();};},[checkin]);
 const addGoal=()=>{const title=goalText.trim();if(!title)return;const g:Goal={id:uid(),title:title.slice(0,200),done:false,created_at:now()};setData(d=>({...d,goals:[...d.goals,g]}));setGoalText('');if(modeRef.current==='cloud')void saveGoal(g).catch(warn);};
 const updateGoal=(g:Goal)=>{const next={...g,done:!g.done};setData(d=>({...d,goals:d.goals.map(x=>x.id===g.id?next:x)}));if(modeRef.current==='cloud')void saveGoal(next).catch(warn);};
 const deleteGoal=(id:string)=>{setData(d=>({...d,goals:d.goals.filter(g=>g.id!==id)}));if(modeRef.current==='cloud')void removeGoal(id).catch(warn);};
 if(splash)return <div className="splash"><div className="splash-halo"/><img src={mascot} alt="BRO" className="splash-mascot"/><div className="splash-brand">bro<span>.</span></div><p>your AI homie is waking up<span className="dots">...</span></p><div className="splash-progress"><i/></div></div>;
 if(!data.profile.onboarded)return <Onboarding onFinish={finish}/>;
 return <div className="app">
 <aside className={'sidebar '+(menuOpen?'show':'')}>
 <div className="sidebar-head"><Logo/><button className="icon-btn sidebar-close" aria-label="Close menu" onClick={()=>setMenuOpen(false)}><X size={18}/></button></div>
 <button className="new-chat" onClick={newChat}><Plus size={19}/> New chat <span>⌘ K</span></button>
 <div className="sidebar-nav"><button className={view==='chat'?'selected':''} onClick={()=>{setView('chat');setMenuOpen(false);}}><MessageCircle size={18}/> Chat <span className="nav-dot"/></button><button className={view==='goals'?'selected':''} onClick={()=>{setView('goals');setMenuOpen(false);}}><Target size={18}/> My goals <span className="nav-count">{data.goals.filter(x=>!x.done).length}</span></button></div>
 <div className="sidebar-divider"/><div className="sidebar-section-head">YOUR CONVERSATIONS <MoreHorizontal size={17}/></div>
 <div className="history">{data.conversations.map(c=><button key={c.id} className={'history-item '+(data.activeConversationId===c.id&&view==='chat'?'active':'')} onClick={()=>{setData(d=>({...d,activeConversationId:c.id}));setView('chat');setMenuOpen(false);}}><MessageCircle size={16}/><span>{c.title}</span></button>)}</div>
 <div className="sidebar-bottom"><div className="sidebar-tip"><Sparkles size={17}/><p><b>made for real conversations.</b><br/>No awkward robot energy here.</p></div><button className={'settings-nav '+(view==='settings'?'selected':'')} onClick={()=>{setView('settings');setMenuOpen(false);}}><Settings2 size={18}/> Settings</button><div className="profile-chip"><span>{data.profile.name.slice(0,1).toUpperCase()}</span><div><b>{data.profile.name}</b><small>{mode==='cloud'?'Connected':'Local preview'}</small></div><span className="online"/></div></div>
 </aside>
 {menuOpen&&<button className="mobile-mask" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>}
 <main className="main">
 <header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Menu size={22}/></button><div className="topbar-title"><img src={mark} alt=""/><div><strong>{view==='chat'?'bro.':view==='goals'?'your goals':'settings'}</strong><small>{view==='chat'?'your AI homie, always around':view==='goals'?'the stuff you’re making happen':'make BRO yours'}</small></div></div><div className="topbar-right"><span className={'mode-pill '+(mode==='cloud'?'live':'')} >{mode==='cloud'?<Cloud size={14}/>:<CloudOff size={14}/>} {mode==='cloud'?'AI connected':mode==='connecting'?'Connecting':'Preview mode'}</span><div className="online-pill"><i/> online</div></div></header>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss"><X size={16}/></button></div>}
 {view==='chat'?<><div className="chat-scroll">
 {shown.length===0?<div className="empty-chat"><div className="hero-graphic"><span className="hero-spark spark-left">✦</span><img src={mascot} alt="Your friendly blue BRO mascot"/><span className="hero-spark spark-right">✧</span></div><div className="eyebrow center"><Sparkles size={14}/> YOUR PERSONAL AI HOMIE</div><h1>yo, {data.profile.name.split(' ')[0]} <span>👋</span></h1><p>what's on your mind? big plans, random thoughts, or just wanna talk — i'm here for it.</p><div className="suggestions">{suggestions.map(s=><button key={s.label} onClick={()=>void send(s.prompt)}><s.icon size={20}/><span>{s.label}</span><ArrowRight size={16}/></button>)}</div><img className="empty-sky" src={sky} alt="Decorative sky and clouds"/></div>:
 <div className="messages"><div className="chat-day">TODAY · YOU & BRO</div>{shown.map(m=><Bubble key={m.id} message={m}/>)}{busy&&<div className="bubble-row ai"><img className="avatar" src={mark} alt="BRO"/><div className="typing"><span/><span/><span/></div></div>}<div ref={endRef}/></div>}
 </div><div className="composer-area"><div className="composer"><textarea aria-label="Message BRO" placeholder="Message BRO..." value={composer} maxLength={3000} rows={1} onChange={e=>setComposer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}}/><button aria-label="Send message" className="send-btn" disabled={!composer.trim()||busy||mode==='connecting'} onClick={()=>void send()}><Send size={18}/></button></div><div className="composer-hint"><span>{mode==='cloud'?'Personalized with your goals and memories':'Preview replies are scripted · Connect Supabase for real AI'}</span><span>Enter to send · Shift+Enter for a line</span></div></div></>:
 view==='goals'?<section className="page goals-page"><div className="page-badge"><Target size={16}/> THE BIG PICTURE</div><h1>your goals, <em>our mission.</em></h1><p>Tell me what you're building or working toward. I'll remember it and bring it up when it's useful.</p><div className="add-goal"><input aria-label="New goal" placeholder="e.g. launch my first app..." value={goalText} maxLength={200} onChange={e=>setGoalText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addGoal();}}/><button className="primary" disabled={!goalText.trim()} onClick={addGoal}><Plus size={18}/> Add goal</button></div><div className="goal-stats"><span><b>{data.goals.length}</b> total goals</span><span><b>{data.goals.filter(x=>x.done).length}</b> completed</span></div><div className="goal-list">{data.goals.length?data.goals.map(g=><div className={'goal-item '+(g.done?'done':'')} key={g.id}><button aria-label={g.done?'Mark incomplete':'Mark complete'} className="goal-check" onClick={()=>updateGoal(g)}>{g.done&&<Check size={16}/>}</button><div><b>{g.title}</b><small>{g.done?'you did it! 🎉':'on your list · added '+new Date(g.created_at).toLocaleDateString()}</small></div><button className="icon-btn" aria-label="Delete goal" onClick={()=>deleteGoal(g.id)}><Trash2 size={17}/></button></div>):<div className="no-goals"><Target size={27}/><b>Nothing here yet</b><p>Add a goal and we’ll have something to work toward together.</p></div>}</div></section>:
 <section className="page settings-page"><div className="page-badge"><WandSparkles size={16}/> PERSONALIZE YOUR BRO</div><h1>your space, <em>your rules.</em></h1><p>Set the vibe. You’re always in control of when I check in.</p><div className="settings-card"><h3><Heart size={19}/> About you</h3><label htmlFor="profile-name">WHAT SHOULD I CALL YOU?</label><input id="profile-name" maxLength={50} value={data.profile.name} onChange={e=>{const p={...data.profile,name:e.target.value};setData(d=>({...d,profile:p}));}} onBlur={()=>persistProfile(dataRef.current.profile,dataRef.current.settings)}/><label htmlFor="profile-work">WHAT DO YOU DO?</label><input id="profile-work" maxLength={90} value={data.profile.occupation} onChange={e=>{setData(d=>({...d,profile:{...d.profile,occupation:e.target.value}}));}} onBlur={()=>persistProfile(dataRef.current.profile,dataRef.current.settings)}/><label htmlFor="profile-about">ABOUT YOU (OPTIONAL)</label><textarea id="profile-about" rows={3} maxLength={500} value={data.profile.about} onChange={e=>setData(d=>({...d,profile:{...d.profile,about:e.target.value}}))} onBlur={()=>persistProfile(dataRef.current.profile,dataRef.current.settings)}/></div>
 <div className="settings-card"><h3><Bell size={19}/> Check-ins & notifications</h3><div className="setting-row"><div><b>Text me first</b><small>Allow BRO to occasionally initiate conversations.</small></div><Toggle label="Text me first" value={data.settings.proactive} onChange={v=>patchSettings({proactive:v,notifications:v?dataRef.current.settings.notifications:false})}/></div><div className="setting-row"><div><b>Desktop notifications</b><small>Show a popup when BRO checks in.</small></div><Toggle label="Desktop notifications" value={data.settings.notifications} onChange={v=>patchSettings({notifications:v})}/></div><label htmlFor="frequency">HOW OFTEN SHOULD I CHECK IN?</label><select id="frequency" value={data.settings.frequency} onChange={e=>patchSettings({frequency:e.target.value as Frequency})}><option value="chill">Chill — every 8h at most</option><option value="balanced">Balanced — every 4h at most</option><option value="chaotic">Chaotic — every 90 min at most</option></select><div className="setting-row"><div><b>Quiet hours</b><small>No interruptions while you’re sleeping.</small></div><Toggle label="Quiet hours" value={data.settings.quietHours} onChange={v=>patchSettings({quietHours:v})}/></div>{data.settings.quietHours&&<div className="quiet-fields"><label>From <input type="time" value={data.settings.quietStart} onChange={e=>patchSettings({quietStart:e.target.value})}/></label><Moon size={17}/><label>Until <input type="time" value={data.settings.quietEnd} onChange={e=>patchSettings({quietEnd:e.target.value})}/></label></div>}</div>
 <div className="settings-card"><h3><Settings2 size={19}/> Desktop app</h3><div className="setting-row"><div><b>Launch at startup</b><small>Keep BRO around when your computer boots.</small></div><Toggle label="Launch at startup" value={data.settings.launchAtStartup} onChange={v=>{void window.broDesktop?.setLaunchAtStartup(v).then(actual=>patchSettings({launchAtStartup:actual}));if(!window.broDesktop)patchSettings({launchAtStartup:v});}}/></div><button className="secondary" onClick={()=>void window.broDesktop?.notify('yo! it’s BRO 💙','Notifications are working.')}><Bell size={16}/> Test notification</button></div><p className="settings-foot"><ShieldCheck size={15}/> BRO is an AI. We don’t access your camera, microphone, files, or screen.</p></section>}
 </main></div>;
}
